# Default
test:
	pytest -v

# Environments
test-qa:
	ENV=QA pytest -m qa

test-qa-headed:
	ENV=QA pytest -m qa --headed

test-staging:
	ENV=staging pytest -m stg

test-staging-headed:
    ENV=staging pytest -m stg --headed